include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    require_trailing_commas: true
    always_use_package_imports: true
    prefer_const_constructors: true
    package_names: true
    camel_case_extensions: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.drift.dart"
  errors:
    invalid_annotation_target: ignore
    missing_return: error
  plugins:
    - custom_lint
