name: flutterquiz
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Web
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.7
  riverpod_annotation: ^2.1.2
  freezed_annotation: ^2.4.1
  go_router: ^10.1.0
  auto_size_text: ^3.0.0
  supabase_flutter: ^1.10.14
  url_launcher: ^6.1.12
  flutter_rating_bar: ^4.0.1

  # Logging
  logging: ^1.2.0
  logging_appenders: ^1.2.0+1
  collection: ^1.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.2.6
  freezed: ^2.4.2
  riverpod_lint: ^2.0.1
  dio: ^5.3.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
